### ISSUE TITLE
Update Sainath.txt 

### ISSUE THREAD

**Issue by SainathPoojary** [saumya1singh/DemoWebsite#30]
Hey @SaumyaSingh1, I want to update Sainath.txt in "DemoWebsite/Assignments/" 
Please Assign it to me.

**Comment by SaumyaSingh1** [comment]
sure

**Comment by SainathPoojary** [comment]
Hey @SaumyaSingh1, the Person to whom the issue is assigned, does he is responsible for Closing the issue or the owner will do it.

**Comment by SaumyaSingh1** [comment]
Hi @SainathPoojary! 

If the issue is no more needed or is solved and you both know/understand this then either of them can do. 
For now, let the owner handle all these things, sounds good?

**Comment by SaumyaSingh1** [comment]
Do you want me to close this issue :)? @SainathPoojary
